# Generated by Django 4.2.29 on 2026-04-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceplan',
            name='practice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('coach', 'Coach'), ('player', 'Player'), ('admin', 'Admin')], default='coach', max_length=20),
        ),
    ]
